chore: update test.yml github action

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -11,12 +11,12 @@ jobs:
     runs-on: ${{ matrix.os }}
     strategy:
       matrix:
-        os: [ ubuntu-latest, macos-latest ]
+        os: [ubuntu-latest, macos-latest]
 
     steps:
       - name: checkout
         uses: actions/checkout@v6
-        
+
       - name: setup go
         uses: actions/setup-go@v6
         with:
@@ -39,7 +39,7 @@ jobs:
       - name: test
         env:
           GITHUB_TOKEN: ${{ matrix.os == 'ubuntu-latest' && secrets.GITHUB_TOKEN || '' }} # Needed for GitHub badge storer integration test
-        run: go test -p 1 ./... -v -timeout=0  -failfast  -count=1 -coverpkg=./pkg/... -coverprofile=cover.out  -skip "^TestOSN2024KRLMALT$|^TestOSN2024KRL$" # skip test yang lama selesainya
+        run: go test -p 1 ./... -v -timeout=0  -failfast  -count=1 -coverpkg=./pkg/...  -coverprofile=${{ matrix.os }}-profile  -skip "^TestOSN2024KRLMALT$|^TestOSN2024KRL$" # skip test yang lama selesainya
         # note: tests harus tidak concurrent (-p 1) karena kita setiap TestFunction pada tests/shortestpath, tests/shortestpath_crp_alt, tests/query write ke file landmark yang sama
 
       - name: upload cover profile artifact
@@ -49,81 +49,79 @@ jobs:
           path: ${{ matrix.os }}-profile
           if-no-files-found: error
 
-
   check-coverage:
-      runs-on: ubuntu-latest
-      needs: test
+    runs-on: ubuntu-latest
+    needs: test
 
-      steps:
-        - name: checkout
-          uses: actions/checkout@v6
-          
+    steps:
+      - name: checkout
+        uses: actions/checkout@v6
 
-        - name: download ubuntu-latest-profile
-          uses: actions/download-artifact@v8
-          with:
-            name: ubuntu-latest-profile
-        - name: download macos-latest-profile
-          uses: actions/download-artifact@v8
-          with:
-            name: macos-latest-profile
-       
-        - name: download artifact (main.breakdown)
-          id: download-main-breakdown
-          uses: dawidd6/action-download-artifact@v20
-          with:
-            branch: main
-            workflow_conclusion: success
-            name: main.breakdown
-            if_no_artifact_found: warn
+      - name: download ubuntu-latest-profile
+        uses: actions/download-artifact@v8
+        with:
+          name: ubuntu-latest-profile
+      - name: download macos-latest-profile
+        uses: actions/download-artifact@v8
+        with:
+          name: macos-latest-profile
 
-        - name: check test coverage
-          id: coverage
-          uses: vladopajic/go-test-coverage@v2
-          continue-on-error: true # Should fail after coverage comment is posted
-          with:
-            config: ./.github/.testcoverage.yml
-            profile: ubuntu-latest-profile,macos-latest-profile
-            git-branch: badges
-            git-token: ${{ github.ref_name == 'main' && secrets.GITHUB_TOKEN || '' }}
-            breakdown-file-name: ${{ github.ref_name == 'main' && 'main.breakdown' || '' }}
-            diff-base-breakdown-file-name: ${{ steps.download-main-breakdown.outputs.found_artifact == 'true' && 'main.breakdown' || '' }}
-  
-        - name: upload artifact (main.breakdown)
-          uses: actions/upload-artifact@v7
-          if: github.ref_name == 'main'
-          with:
-            name: main.breakdown
-            path: main.breakdown
-            if-no-files-found: error
+      - name: download artifact (main.breakdown)
+        id: download-main-breakdown
+        uses: dawidd6/action-download-artifact@v20
+        with:
+          branch: main
+          workflow_conclusion: success
+          name: main.breakdown
+          if_no_artifact_found: warn
 
-        - name: find pull request ID
-          run: |
-            if [ "${{ github.event_name }}" == "pull_request" ]; then
-              echo "pull_request_id=${{ github.event.pull_request.number }}" >> $GITHUB_ENV
+      - name: check test coverage
+        id: coverage
+        uses: vladopajic/go-test-coverage@v2
+        continue-on-error: true # Should fail after coverage comment is posted
+        with:
+          config: ./.github/.testcoverage.yml
+          profile: ubuntu-latest-profile,macos-latest-profile
+          git-branch: badges
+          git-token: ${{ github.ref_name == 'main' && secrets.GITHUB_TOKEN || '' }}
+          breakdown-file-name: ${{ github.ref_name == 'main' && 'main.breakdown' || '' }}
+          diff-base-breakdown-file-name: ${{ steps.download-main-breakdown.outputs.found_artifact == 'true' && 'main.breakdown' || '' }}
+
+      - name: upload artifact (main.breakdown)
+        uses: actions/upload-artifact@v7
+        if: github.ref_name == 'main'
+        with:
+          name: main.breakdown
+          path: main.breakdown
+          if-no-files-found: error
+
+      - name: find pull request ID
+        run: |
+          if [ "${{ github.event_name }}" == "pull_request" ]; then
+            echo "pull_request_id=${{ github.event.pull_request.number }}" >> $GITHUB_ENV
+          else
+            PR_DATA=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+              "https://api.github.com/repos/${{ github.repository }}/pulls?head=${{ github.repository_owner }}:${{ github.ref_name }}&state=open")
+            PR_ID=$(echo "$PR_DATA" | jq -r '.[0].number')
+            if [ "$PR_ID" != "null" ]; then
+              echo "pull_request_id=$PR_ID" >> $GITHUB_ENV
             else
-              PR_DATA=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
-                "https://api.github.com/repos/${{ github.repository }}/pulls?head=${{ github.repository_owner }}:${{ github.ref_name }}&state=open")
-              PR_ID=$(echo "$PR_DATA" | jq -r '.[0].number')
-              if [ "$PR_ID" != "null" ]; then
-                echo "pull_request_id=$PR_ID" >> $GITHUB_ENV
-              else
-                echo "No open pull request found for this branch."
-              fi
+              echo "No open pull request found for this branch."
             fi
-        - name: post coverage report
-          if: env.pull_request_id
-          uses: thollander/actions-comment-pull-request@v3
-          with:
-            github-token: ${{ secrets.GITHUB_TOKEN }}
-            comment-tag: coverage-report
-            pr-number: ${{ env.pull_request_id }}
-            message: |
-              go-test-coverage report:
-              ``` 
-              ${{ fromJSON(steps.coverage.outputs.report) }}```
-  
-        - name: "finally check coverage"
-          if: steps.coverage.outcome == 'failure'
-          shell: bash
-          run: echo "coverage check failed" && exit 1
+          fi
+      - name: post coverage report
+        if: env.pull_request_id
+        uses: thollander/actions-comment-pull-request@v3
+        with:
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          comment-tag: coverage-report
+          pr-number: ${{ env.pull_request_id }}
+          message: |
+            go-test-coverage report:
+            ``` 
+            ${{ fromJSON(steps.coverage.outputs.report) }}```
+
+      - name: "finally check coverage"
+        if: steps.coverage.outcome == 'failure'
+        shell: bash
+        run: echo "coverage check failed" && exit 1
